window.comparisonData = {
  common: {
    resolution: "1080p",
    aspectRatio: "16:9",
    seed: 9681,
    frameType: "first frame",
    finalDuration: 5,
    finalFps: 30,
    finalFrames: 150,
    finalAudio: false,
  },
  cases: [
    {
      id: "source-1",
      number: "01",
      title: "Лебеди на закате",
      source: {
        path: "input/1.jpeg",
        filename: "1.jpeg",
        width: 1600,
        height: 1066,
        sizeBytes: 308982,
      },
      task:
        "Два лебедя мягко скользят вправо, оставляя рябь; пейзаж, пирс и вывеска остаются стабильными.",
      models: [
        {
          key: "wan",
          name: "Wan 2.7",
          modelId: "alibaba/wan-2.7",
          provider: "AtlasCloud",
          video: "final/wan-2.7/1.mp4",
          costUsd: 0.5,
          generationTimeSeconds: 125.683,
          requestedDurationSeconds: 5,
          requestedResolution: "1080p",
          requestedAspectRatio: "16:9",
          seed: 9681,
          negativePrompt: "Не отправлен: 716 символов превышают лимит AtlasCloud в 500.",
          jobId: "Zm54oYHDJWkzfDfVKvtT",
          generationId: "gen-vid-1783959330-Rf8NtgLUjM1OGmnQzB37",
          final: {
            width: 1764,
            height: 1174,
            durationSeconds: 5,
            fps: 30,
            frames: 150,
            codec: "H.264 High",
            pixelFormat: "yuv420p",
            bitRate: 25270502,
            sizeBytes: 15796895,
            hasAudio: false,
          },
          processing: "Remux без перекодирования; AAC удалён, нативные 30 fps сохранены.",
          deviations: [
            "Вместо запрошенных 16:9 провайдер вернул 1764×1174 (≈3:2), сохранив геометрию исходника.",
            "Raw содержал AAC и длился 5.038 с; в финале аудио удалено, видеопоток ровно 5.000 с.",
          ],
          review: [
            "Оба лебедя движутся вправо, рябь читается, основные объекты сцены сохранены.",
            "Точную стабильность букв вывески по пяти контрольным кадрам гарантировать нельзя.",
          ],
        },
        {
          key: "veo",
          name: "Veo 3.1 Lite",
          modelId: "google/veo-3.1-lite",
          provider: "Google Vertex",
          video: "final/veo-3.1-lite/1.mp4",
          costUsd: 0.3,
          generationTimeSeconds: 154.822,
          requestedDurationSeconds: 6,
          requestedResolution: "1080p",
          requestedAspectRatio: "16:9",
          seed: 9681,
          negativePrompt: "Отправлен через negativePrompt.",
          jobId: "iVAZz8LTifZ9NsEzzrZr",
          generationId: "gen-vid-1783959561-MsxN1f1uTpCAgwZPbwKL",
          final: {
            width: 1920,
            height: 1080,
            durationSeconds: 5,
            fps: 30,
            frames: 150,
            codec: "H.264 High",
            pixelFormat: "yuv420p",
            bitRate: 9877612,
            sizeBytes: 6176140,
            hasAudio: false,
          },
          processing: "Raw 6 с / 24 fps обрезан до 5 с и motion-interpolated до 30 fps.",
          deviations: [
            "Модель не поддерживает 5 секунд напрямую: запрошено 6 с, затем выполнены trim и интерполяция 24→30 fps.",
            "Исходник помещён в 1920×1080 с заметными pillarbox-полями.",
          ],
          review: [
            "Лебеди скользят вместе, рябь и курортная сцена остаются стабильными.",
            "Широкий холст стандартизирован, но полезная площадь кадра меньше из-за полей.",
          ],
        },
      ],
    },
    {
      id: "source-2",
      number: "02",
      title: "Гольфист после удара",
      source: {
        path: "input/2.jpeg",
        filename: "2.jpeg",
        width: 1600,
        height: 1200,
        sizeBytes: 357606,
      },
      task:
        "Гольфист завершает движение, расслабляет плечи и продолжает смотреть вправо; поле и инвентарь стабильны.",
      models: [
        {
          key: "wan",
          name: "Wan 2.7",
          modelId: "alibaba/wan-2.7",
          provider: "AtlasCloud",
          video: "final/wan-2.7/2.mp4",
          costUsd: 0.5,
          generationTimeSeconds: 95.017,
          requestedDurationSeconds: 5,
          requestedResolution: "1080p",
          requestedAspectRatio: "16:9",
          seed: 9681,
          negativePrompt: "Не отправлен: 622 символа превышают лимит AtlasCloud в 500.",
          jobId: "SQna0DP7d2eunTY1bkbB",
          generationId: "gen-vid-1783959461-jMYv98YuNKnGqtoHzWZw",
          final: {
            width: 1662,
            height: 1246,
            durationSeconds: 5,
            fps: 30,
            frames: 150,
            codec: "H.264 High",
            pixelFormat: "yuv420p",
            bitRate: 28881558,
            sizeBytes: 18053849,
            hasAudio: false,
          },
          processing: "Remux без перекодирования; AAC удалён, нативные 30 fps сохранены.",
          deviations: [
            "Вместо запрошенных 16:9 провайдер вернул 1662×1246 (≈4:3), сохранив геометрию исходника.",
            "Гольфист опускает клюшку и заметно разворачивается к камере — движение шире заданного.",
          ],
          review: [
            "Сумка, пруд, бункеры, линия деревьев и дневной свет стабильны.",
            "Raw содержал AAC и длился 5.038 с; финал очищен до точных 5.000 с без аудио.",
          ],
        },
        {
          key: "veo",
          name: "Veo 3.1 Lite",
          modelId: "google/veo-3.1-lite",
          provider: "Google Vertex",
          video: "final/veo-3.1-lite/2.mp4",
          costUsd: 0.3,
          generationTimeSeconds: 155.228,
          requestedDurationSeconds: 6,
          requestedResolution: "1080p",
          requestedAspectRatio: "16:9",
          seed: 9681,
          negativePrompt: "Отправлен через negativePrompt.",
          jobId: "WXZrhHc2ZkaH0v8kyAPE",
          generationId: "gen-vid-1783959765-d05nxkmU1pFfPsgzt46Z",
          final: {
            width: 1920,
            height: 1080,
            durationSeconds: 5,
            fps: 30,
            frames: 150,
            codec: "H.264 High",
            pixelFormat: "yuv420p",
            bitRate: 8086830,
            sizeBytes: 5056905,
            hasAudio: false,
          },
          processing: "Raw 6 с / 24 fps обрезан до 5 с и motion-interpolated до 30 fps.",
          deviations: [
            "Модель не поддерживает 5 секунд напрямую: запрошено 6 с, затем выполнены trim и интерполяция 24→30 fps.",
            "Гольфист опускает клюшку и разворачивается сильнее минимального движения из промпта.",
          ],
          review: [
            "Поле, сумка, пруд и небо сохраняются стабильно.",
            "Исходник помещён в 1920×1080 с pillarbox-полями.",
          ],
        },
      ],
    },
  ],
};
